language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r private_files/tests/requirements/django-1.11.txt
# command to run tests
script:
  - ./runtests.py