language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies

env:
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0

install:
  - pip install -r private_files/tests/requirements/django-${DJANGO}.txt
# command to run tests
script:
  - ./runtests.py